name: Create release

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'A short description of the changes.'
        type: string
        required: true
      tag:
        description: 'The version identifier for the new release.'
        type: string
        required: true
      prerelease:
        description: 'This is a pre-release.'
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/00_build.yml
    with:
      upload_artifacts: true

  create-release-body:
    uses: ./.github/workflows/01-00_create-release-body.yml
    with:
      description: ${{ inputs.description }}
      tag: ${{ inputs.tag }}
      prerelease: ${{ inputs.prerelease }}

  create-release:
    needs: [build, create-release-body]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout livesplit_refunct
        uses: actions/checkout@v4

      - name: Load livesplit_refunct.wasm artifact
        uses: actions/download-artifact@v4
        with:
          name: livesplit_refunct-build-artifacts

      - name: Delete livesplit_refunct.wasm artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: livesplit_refunct-build-artifacts
          failOnError: false

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: >
            livesplit_refunct
            ${{ inputs.tag }}
          body: ${{ needs.create-release-body.outputs.body }}
          prerelease: ${{ inputs.prerelease }}

      - name: Upload livesplit_refunct.wasm as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./livesplit_refunct.wasm
          asset_name: livesplit_refunct.wasm
          asset_content_type: application/wasm
