name: Build livesplit_refunct

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout livesplit_refunct
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          components: rust-src
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Build livesplit_refunct
        run: >
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu;
          cargo b --release --locked

      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: livesplit_refunct
          path: target/wasm32-unknown-unknown/release/livesplit_refunct.wasm